backend:
  name: github
  branch: master
  repo: paduc/test-nextjs-netlify
  api_root: https://api.github.com
  auth_scope: repo
  base_url: https://betagouv-cms-auth.osc-secnum-fr1.scalingo.io
  commit_messages:
    create: Création de {{slug}} dans {{collection}} !
    update: Mise à jour de {{slug}} dans {{collection}}
    delete: Suppression de {{slug}} dans {{collection}}
    uploadMedia: Nouvelle image {{path}}
    deleteMedia: Suppression de l'image {{path}}
  open_authoring: true
  always_fork: true
  squash_merges: true
  use_graphql: true

media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Périodes"
      name: "periodes"
      file: "content/periodes.json"
      fields:
        - { label: "Numéro de périodes", name: "numero", widget: "string"}
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Nom de la startup", name: "nomStartup", widget: "string"}
        - { label: "Sous titre de la startup", name: "sousTitreStartup", widget: "string"}
        - { label: "Corps", name: "body", widget: "markdown"}